version: '3'
services:
  postgres:
    image: 'postgres:latest'
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '127.0.0.1:5432:5432'
    environment:
      - PGHOST=postgres
      - PGUSER=postgres
      - PGPASSWORD=packet
      - PGPORT=5432
  game:
    build:
      dockerfile: ./Dockerfile
      context: ./
    ports:
      - '3000:3000'
    container_name: game
    volumes:
      - /app/node_modules
      - ./.:/app
    depends_on:
      - postgres
    environment:
      - PGHOST=postgres
      - PGUSER=postgres
      - PGPASSWORD=packet
      - PGDATABASE=game
      - PGPORT=5432
volumes:
  postgres: